# Generated by Django 3.1.7 on 2021-03-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.TextField(default='26 Mar 1971'),
        ),
    ]
