<<<<<<< HEAD
# Generated by Django 3.1.6 on 2021-03-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
=======
# Generated by Django 3.1.6 on 2021-03-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
>>>>>>> 147bda33da003c925290f936386d23df74250f3f
