# Generated by Django 3.1.7 on 2021-04-02 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210403_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joiningDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
