# Generated by Django 3.1.7 on 2021-04-02 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210403_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
