# Generated by Django 3.1.7 on 2021-04-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210403_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginStatus',
            field=models.BooleanField(default=False),
        ),
    ]
