# Generated by Django 3.1.7 on 2021-04-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_loginstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loginStatus',
        ),
    ]
