# Generated by Django 3.1.7 on 2021-04-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210409_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentBalance',
            field=models.FloatField(default=0.0),
        ),
    ]
