# Generated by Django 3.1.7 on 2021-04-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_currentbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='totalWithdrawn',
            new_name='totalRepaid',
        ),
    ]
