# Generated by Django 3.1.7 on 2021-05-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210411_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.FileField(default='default.jpg', upload_to='profile'),
        ),
    ]
