# Generated by Django 3.1.7 on 2021-04-10 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPssDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyUserEmail', models.EmailField(max_length=254)),
                ('joiningDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
