# Generated by Django 3.1.7 on 2021-04-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpssdb',
            name='secritKey',
            field=models.TextField(default=''),
        ),
    ]
