# Generated by Django 3.1.6 on 2021-03-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_auto_20210327_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_Name', models.TextField()),
                ('proj_Location', models.TextField()),
                ('profit_Indicator1', models.FloatField(default=0.0)),
                ('profit_Indicator2', models.FloatField(default=0.0)),
                ('profit_Indicator3', models.FloatField(default=0.0)),
                ('feedback1', models.TextField()),
                ('feedback2', models.TextField()),
                ('feedback3', models.TextField()),
                ('entr_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
