# Generated by Django 3.1.6 on 2021-03-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='proj_Budget',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='proj_Funded',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
