# Generated by Django 3.1.7 on 2021-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0004_auto_20210403_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='proj_details',
            field=models.TextField(default=''),
        ),
    ]
