# Generated by Django 3.1.7 on 2021-04-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0006_auto_20210409_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='proj_status',
            field=models.TextField(default='new'),
        ),
    ]
