# Generated by Django 3.1.6 on 2021-03-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrepreneur', '0002_auto_20210327_1804'),
        ('user', '0009_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('investor_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
                ('proj_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entrepreneur.projects')),
            ],
        ),
    ]
